---
abstract: "Keep connection to OS Inferno's registry(4) and it tasks"
author:
  - 'Alex Efros  C<< <powerman-asdf@ya.ru> >>'
  - 'Alex Efros <powerman-asdf@ya.ru>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Inferno-RegMgr
no_index:
  directory:
    - inc
    - t
requires:
  EV: 0
  IO::Stream: 0
  Perl6::Export::Attrs: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001004
