#!/dis/sh

# (for perl) plain tcp interface to /mnt/registry/{new,find,event}
listen -A tcp!127.0.0.1!16675 { cat >/mnt/registry/new & }
listen -A tcp!127.0.0.1!26675 { {
    read >[1=3]; read -o 0 0 <[0=3]; cat >[1=0] <[0=3]
    } <>[3]/mnt/registry/find & }
# 'echo READY' needed to workaround race: between connecting to tcp port
# and opening event file may happens some events which will be lost in
# case client expect to get ALL events after establishing connection
listen -A tcp!127.0.0.1!36675 { {
    echo READY; cat
    } </mnt/registry/event & }

